### PR TITLE
Feat: Added new assets for new additions

### PR DESCRIPTION
**Pull request by Mayor-Rhymes**

### CODE REVIEW

**Comment by ArinzeJeffrey-droid** [comment]
Oh damn, the pictures of pizzas got me feeling hungry LMAO

**Comment by ArinzeJeffrey-droid** [comment]
Maybe create a `__types__` directory and create a file in there to keep your types. Because the `mockData` file should only hold mock data not types as the name says.

**Comment by Mayor-Rhymes** [comment]
> Maybe create a `__types__` directory and create a file in there to keep your types. Because the `mockData` file should only hold mock data not types as the name says.

@ArinzeJeffrey-droid I noticed that you used `__types__` to describe the directory. I am actually confused about that name. Is there something special about the way it is written? Good morning boss

**Review by ArinzeJeffrey-droid — APPROVED** [review]

**Comment by ArinzeJeffrey-droid** [comment]
@Mayor-Rhymes It just a personal preference I like naming my types folder `__types__`

**Comment by Mayor-Rhymes** [comment]
> @Mayor-Rhymes It just a personal preference I like naming my types folder `__types__`

I see.

**Pull request merged**
